name = "Vanilla Sky"
author = "jsorrell"
version = "1.20.1-1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c621a00b618d46be99d778f95701baa40da7f3cc25d1e709fefbb7a4f6f78f7b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
