name = "Vanilla Sky"
author = "jsorrell"
version = "1.20.1-1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c96ef31e47d348be544cb25230e40865e44d2a1c397e421abdc4188033105ba"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
